version: '3'

services:
  easycwmp:
    build: 
      context: . 
    container_name: goacs-easycwmp
    stdin_open: true
    tty: true
    environment:
      - ACS_URL=http://172.23.0.1:8085/acs
      - DEVICE_SERIAL=DEADBEEF123456
